# Generated by Django 3.0 on 2020-11-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categire', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_categire', models.CharField(max_length=100, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_status', models.CharField(max_length=10, null=True)),
                ('product_sizes', models.CharField(choices=[('MSL', 'MSL'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXl', 'XXl')], max_length=30, null=True)),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
