# Generated by Django 3.0 on 2020-11-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_auto_20201111_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_categire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.Categires'),
        ),
    ]
