# Generated by Django 3.0 on 2020-11-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_auto_20201111_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categirie', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_sizes',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_status',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='current_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_for',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sizes',
            field=models.CharField(choices=[('XSML', 'XSML'), ('M', 'M'), ('SML', 'SML'), ('L', 'L'), ('XL', 'XL'), ('XXl', 'XXL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='valid_upto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_categire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.Categire'),
        ),
        migrations.DeleteModel(
            name='Categires',
        ),
    ]
