# Generated by Django 3.0 on 2020-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_auto_20201112_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='current_status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
