# Generated by Django 3.0 on 2020-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_auto_20201114_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_for',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
