# Generated by Django 3.0 on 2020-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_auto_20201114_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sizes',
            field=models.CharField(choices=[('XSML', 'XSML'), ('M', 'M'), ('SML', 'SML'), ('L', 'L'), ('XL', 'XL'), ('XXl', 'XXL'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10, null=True),
        ),
    ]
