# Generated by Django 3.0 on 2020-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_auto_20201115_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='valid_upto',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
