# Generated by Django 3.0 on 2020-11-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingapp', '0010_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtocartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
