# Generated by Django 3.0 on 2020-11-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0011_addtocartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='pro',
        ),
    ]
