# Generated by Django 3.0 on 2020-11-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0013_auto_20201119_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='categire',
        ),
    ]
