# Generated by Django 3.0 on 2020-11-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_remove_addtocartmodel_categire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='product_for',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='size',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='valid_upto',
        ),
        migrations.AddField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
    ]
