# Generated by Django 3.0 on 2020-11-23 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingapp', '0016_auto_20201120_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('alternative_mobile', models.IntegerField(null=True)),
                ('house_no', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('address1', models.CharField(max_length=50, null=True)),
                ('address2', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_status', models.CharField(default='Not Done', max_length=500)),
                ('amount', models.FloatField(null=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('shipped', 'shipped'), ('out_for_delivered', 'out_for_delivered')], max_length=50, null=True)),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
