# Generated by Django 3.0 on 2020-11-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0017_auto_20201123_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
    ]
