# Generated by Django 3.0 on 2020-11-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_auto_20201125_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='house_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
    ]
