# Generated by Django 3.0 on 2020-11-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0019_auto_20201125_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
