# Generated by Django 3.0 on 2020-11-25 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingapp', '0020_auto_20201126_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.ProductModel'),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('address', models.TextField(null=True)),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
